spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/don_pipeline
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
  flyway:
    enabled: true
    default-schema: api_bd3
    baseline-on-migrate: true
server:
  port: 8080
# Debug true se for debugar
debug: false